// Declares the app's IPC commands so Tauri generates `allow-<command>` permissions
// (permissions/autogenerated/) and `removeUnusedCommands` keeps them (docs/02 section 7).
// Keep this list equal to `commands::handler()`.
const COMMANDS: &[&str] = &[
    "get_view",
    "get_event",
    "list_accounts",
    "list_calendars",
    "set_calendar_visible",
    "create_event",
    "update_event",
    "delete_event",
    "move_event_account",
    "add_account",
    "remove_account",
    "open_url",
    "sync_now",
    "get_colors",
    "rsvp",
    "get_settings",
    "set_settings",
    "test_push",
    "goa_status",
    "goa_disable_calendars",
    "add_ical_calendar",
    "dev_dump",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
