// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json. Do not edit.
export const LAYOUT = {
  topbar_height: "64px",
  sidebar_width: "256px",
  sidebar_padding: "19px",
  gutter_width: "102.34px",
  gutter_width_two_zones: "102.34px",
  hour_row_height: "60px",
  day_header_height: "84px",
  mini_cal_cell: "31.84px",
  create_button_left: "16px",
  create_button_top: "76px",
  create_menu_left: "16px",
  create_menu_top: "136px",
  main_left: "256px",
  main_width: "1168px",
  main_top: "64px",
  week_header_height: "84px",
  allday_chip_row_height: "24px",
  day_column_pad: "9px",
  chip_width_factor: "1.7",
  chip_height_gap: "2px",
  week_initial_scroll: "420px",
  main_gap_right: "16px",
  main_gap_bottom: "16px",
  week_scroll_now_margin: "90px",
  chip_radius: "6px",
  chip_padding_left: "8px",
  chip_min_height: "11px",
} as const;

/** Numeric part of a layout token ("60px" → 60, "1.7" → 1.7). */
export const layoutNumber = (v: string): number => parseFloat(v);
