// GENERATED by scripts/gen-m3-tokens.mjs from docs/design/m3/theme.json. Do not edit.
export const MOTION = {
  nav_slide_duration: "200ms",
  nav_slide_easing: "cubic-bezier(0.2, 0, 0, 1)",
  nav_slide_offset: "56px",
  view_fade_duration: "200ms",
  popup_open_duration: "250ms",
  popup_open_easing: "cubic-bezier(0.05, 0.7, 0.1, 1)",
  popup_close_duration: "150ms",
  popup_close_easing: "cubic-bezier(0.3, 0, 0.8, 0.15)",
  popup_rise: "32px",
  tooltip_delay: "500ms",
  tooltip_show_duration: "150ms",
  tooltip_hide_duration: "100ms",
  snackbar_hold_duration: "5000ms",
  snackbar_slide_duration: "250ms",
  drawer_duration: "300ms",
  drawer_easing: "cubic-bezier(0.2, 0, 0, 1)",
} as const;
