// GENERATED by scripts/gen-m3-tokens.mjs from docs/design/m3/theme.json. Do not edit.
export interface ChipColors {
  /** Chip border and calendar dot. */
  color: string;
  /** Chip background. */
  container: string;
  /** Chip text. */
  onContainer: string;
}

/** Stored hex (classic calendar colour from the API or modern event colour) → M3 custom color roles per theme. */
export const COLOR_MAP: Record<string, { light: ChipColors; dark: ChipColors }> = {
  "#ac725e": {"light":{"color":"#85513f","container":"#ffdbcf","onContainer":"#341004"},"dark":{"color":"#fbb7a0","container":"#693a29","onContainer":"#ffdbcf"}},
  "#d06b64": {"light":{"color":"#9b423d","container":"#ffdad6","onContainer":"#410004"},"dark":{"color":"#ffb3ad","container":"#7d2b28","onContainer":"#ffdad6"}},
  "#f83a22": {"light":{"color":"#bd1100","container":"#ffdad4","onContainer":"#400200"},"dark":{"color":"#ffb4a7","container":"#910a00","onContainer":"#ffdad4"}},
  "#fa573c": {"light":{"color":"#b52610","container":"#ffdad3","onContainer":"#3f0300"},"dark":{"color":"#ffb4a6","container":"#900f00","onContainer":"#ffdad3"}},
  "#ff7537": {"light":{"color":"#a63b00","container":"#ffdbce","onContainer":"#370e00"},"dark":{"color":"#ffb598","container":"#7f2b00","onContainer":"#ffdbce"}},
  "#ffad46": {"light":{"color":"#875200","container":"#ffddba","onContainer":"#2b1700"},"dark":{"color":"#ffb866","container":"#673d00","onContainer":"#ffddba"}},
  "#42d692": {"light":{"color":"#006d44","container":"#6efcb4","onContainer":"#002111"},"dark":{"color":"#4ddf9a","container":"#005232","onContainer":"#6efcb4"}},
  "#16a765": {"light":{"color":"#006d3f","container":"#7dfbb0","onContainer":"#00210f"},"dark":{"color":"#5fde96","container":"#00522e","onContainer":"#7dfbb0"}},
  "#7bd148": {"light":{"color":"#2d6c00","container":"#a0f96b","onContainer":"#092100"},"dark":{"color":"#85dc51","container":"#205100","onContainer":"#a0f96b"}},
  "#b3dc6c": {"light":{"color":"#476800","container":"#c7f17e","onContainer":"#131f00"},"dark":{"color":"#abd465","container":"#354e00","onContainer":"#c7f17e"}},
  "#fbe983": {"light":{"color":"#6b5f00","container":"#f5e47e","onContainer":"#201c00"},"dark":{"color":"#d8c866","container":"#514700","onContainer":"#f5e47e"}},
  "#fad165": {"light":{"color":"#765b00","container":"#ffdf93","onContainer":"#241a00"},"dark":{"color":"#eac258","container":"#594400","onContainer":"#ffdf93"}},
  "#92e1c0": {"light":{"color":"#146b51","container":"#a3f3d1","onContainer":"#002116"},"dark":{"color":"#87d6b6","container":"#00513b","onContainer":"#a3f3d1"}},
  "#9fe1e7": {"light":{"color":"#21686d","container":"#aceef4","onContainer":"#002022"},"dark":{"color":"#90d1d7","container":"#004f54","onContainer":"#aceef4"}},
  "#9fc6e7": {"light":{"color":"#3b627f","container":"#cae6ff","onContainer":"#001e30"},"dark":{"color":"#a4cbec","container":"#214a66","onContainer":"#cae6ff"}},
  "#4986e7": {"light":{"color":"#065cbb","container":"#d7e2ff","onContainer":"#001b3f"},"dark":{"color":"#abc7ff","container":"#004590","onContainer":"#d7e2ff"}},
  "#9a9cff": {"light":{"color":"#5254b1","container":"#e1dfff","onContainer":"#08006c"},"dark":{"color":"#c1c1ff","container":"#3a3b98","onContainer":"#e1dfff"}},
  "#b99aff": {"light":{"color":"#6a4cab","container":"#eaddff","onContainer":"#24005b"},"dark":{"color":"#d1bcff","container":"#523391","onContainer":"#eaddff"}},
  "#c2c2c2": {"light":{"color":"#5d5e5f","container":"#e3e2e2","onContainer":"#1a1c1c"},"dark":{"color":"#c6c6c6","container":"#464747","onContainer":"#e3e2e2"}},
  "#cabdbf": {"light":{"color":"#665c5e","container":"#eddfe1","onContainer":"#211a1b"},"dark":{"color":"#d0c3c5","container":"#4d4546","onContainer":"#eddfe1"}},
  "#cca6ac": {"light":{"color":"#75565c","container":"#ffd9df","onContainer":"#2b151a"},"dark":{"color":"#e4bdc3","container":"#5c3f44","onContainer":"#ffd9df"}},
  "#f691b2": {"light":{"color":"#964261","container":"#ffd9e2","onContainer":"#3e001d"},"dark":{"color":"#ffb1c8","container":"#792b49","onContainer":"#ffd9e2"}},
  "#cd74e6": {"light":{"color":"#8d38a7","container":"#fbd7ff","onContainer":"#330044"},"dark":{"color":"#f1afff","container":"#721a8d","onContainer":"#fbd7ff"}},
  "#a47ae2": {"light":{"color":"#7148ad","container":"#eddcff","onContainer":"#280056"},"dark":{"color":"#d7baff","container":"#592f93","onContainer":"#eddcff"}},
  "#7986cb": {"light":{"color":"#4d5a9c","container":"#dee1ff","onContainer":"#021355"},"dark":{"color":"#b9c3ff","container":"#354282","onContainer":"#dee1ff"}},
  "#33b679": {"light":{"color":"#006d43","container":"#7efab7","onContainer":"#002111"},"dark":{"color":"#61dd9c","container":"#005231","onContainer":"#7efab7"}},
  "#8e24aa": {"light":{"color":"#942cb0","container":"#fdd6ff","onContainer":"#340042"},"dark":{"color":"#f3aeff","container":"#790096","onContainer":"#fdd6ff"}},
  "#e67c73": {"light":{"color":"#9b423c","container":"#ffdad6","onContainer":"#410003"},"dark":{"color":"#ffb4ac","container":"#7d2b27","onContainer":"#ffdad6"}},
  "#f6bf26": {"light":{"color":"#775a00","container":"#ffdf9a","onContainer":"#251a00"},"dark":{"color":"#f5bf25","container":"#5a4300","onContainer":"#ffdf9a"}},
  "#f4511e": {"light":{"color":"#b02e00","container":"#ffdbd1","onContainer":"#3b0900"},"dark":{"color":"#ffb5a0","container":"#872100","onContainer":"#ffdbd1"}},
  "#039be5": {"light":{"color":"#006496","container":"#cbe6ff","onContainer":"#001e31"},"dark":{"color":"#90cdff","container":"#004b72","onContainer":"#cbe6ff"}},
  "#616161": {"light":{"color":"#5e5e5e","container":"#e4e2e2","onContainer":"#1b1c1c"},"dark":{"color":"#c7c6c6","container":"#464747","onContainer":"#e4e2e2"}},
  "#3f51b5": {"light":{"color":"#4355b9","container":"#dee0ff","onContainer":"#00105c"},"dark":{"color":"#bac3ff","container":"#293ca0","onContainer":"#dee0ff"}},
  "#0b8043": {"light":{"color":"#006d37","container":"#93f8ae","onContainer":"#00210c"},"dark":{"color":"#77db93","container":"#005228","onContainer":"#93f8ae"}},
  "#d50000": {"light":{"color":"#c00000","container":"#ffdad4","onContainer":"#410000"},"dark":{"color":"#ffb4a8","container":"#930000","onContainer":"#ffdad4"}},
};

/** Event colorId → modern hex (the value the backend stores). */
export const EVENT_COLORS: Record<string, string> = {
  "1": "#7986cb",
  "2": "#33b679",
  "3": "#8e24aa",
  "4": "#e67c73",
  "5": "#f6bf26",
  "6": "#f4511e",
  "7": "#039be5",
  "8": "#616161",
  "9": "#3f51b5",
  "10": "#0b8043",
  "11": "#d50000",
};

/** Event colorId → Google's colour name. */
export const EVENT_COLOR_NAMES: Record<string, string> = {
  "1": "Lavender",
  "2": "Sage",
  "3": "Grape",
  "4": "Flamingo",
  "5": "Banana",
  "6": "Tangerine",
  "7": "Peacock",
  "8": "Graphite",
  "9": "Blueberry",
  "10": "Basil",
  "11": "Tomato",
};

export const LOCAL_CALENDAR_DEFAULT = "#f4511e";
