// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json. Do not edit.
export interface ChipColors {
  bg: string;
  fg: string;
}

/** Stored hex (classic calendar colour or modern event colour) → measured chip colours per theme. */
export const COLOR_MAP: Record<string, { light: ChipColors; dark: ChipColors }> = {
  "#ac725e": {"light":{"bg":"#795548","fg":"#ffffff"},"dark":{"bg":"#957367","fg":"#131314"}},
  "#d06b64": {"light":{"bg":"#e67c73","fg":"#ffffff"},"dark":{"bg":"#d6837a","fg":"#131314"}},
  "#f83a22": {"light":{"bg":"#d50000","fg":"#ffffff"},"dark":{"bg":"#da5234","fg":"#131314"}},
  "#fa573c": {"light":{"bg":"#f4511e","fg":"#ffffff"},"dark":{"bg":"#e3683e","fg":"#131314"}},
  "#ff7537": {"light":{"bg":"#ef6c00","fg":"#ffffff"},"dark":{"bg":"#dd7835","fg":"#131314"}},
  "#ffad46": {"light":{"bg":"#f09300","fg":"#ffffff"},"dark":{"bg":"#e0963c","fg":"#131314"}},
  "#42d692": {"light":{"bg":"#009688","fg":"#ffffff"},"dark":{"bg":"#429a8e","fg":"#131314"}},
  "#16a765": {"light":{"bg":"#0b8043","fg":"#ffffff"},"dark":{"bg":"#489160","fg":"#131314"}},
  "#7bd148": {"light":{"bg":"#7cb342","fg":"#ffffff"},"dark":{"bg":"#85ad59","fg":"#131314"}},
  "#b3dc6c": {"light":{"bg":"#c0ca33","fg":"#ffffff"},"dark":{"bg":"#bcc256","fg":"#131314"}},
  "#fbe983": {"light":{"bg":"#e4c441","fg":"#ffffff"},"dark":{"bg":"#d8be5e","fg":"#131314"}},
  "#fad165": {"light":{"bg":"#f6bf26","fg":"#ffffff"},"dark":{"bg":"#e7ba51","fg":"#131314"}},
  "#92e1c0": {"light":{"bg":"#33b679","fg":"#ffffff"},"dark":{"bg":"#55b080","fg":"#131314"}},
  "#9fe1e7": {"light":{"bg":"#039be5","fg":"#ffffff"},"dark":{"bg":"#4b99d2","fg":"#131314"}},
  "#9fc6e7": {"light":{"bg":"#4285f4","fg":"#ffffff"},"dark":{"bg":"#668be1","fg":"#131314"}},
  "#4986e7": {"light":{"bg":"#3f51b5","fg":"#ffffff"},"dark":{"bg":"#6e72c3","fg":"#131314"}},
  "#9a9cff": {"light":{"bg":"#7986cb","fg":"#ffffff"},"dark":{"bg":"#828bc2","fg":"#131314"}},
  "#b99aff": {"light":{"bg":"#b39ddb","fg":"#ffffff"},"dark":{"bg":"#ae9cce","fg":"#131314"}},
  "#c2c2c2": {"light":{"bg":"#616161","fg":"#ffffff"},"dark":{"bg":"#7c7c7c","fg":"#131314"}},
  "#cabdbf": {"light":{"bg":"#a79b8e","fg":"#ffffff"},"dark":{"bg":"#a5998c","fg":"#131314"}},
  "#cca6ac": {"light":{"bg":"#ad1457","fg":"#ffffff"},"dark":{"bg":"#c05476","fg":"#131314"}},
  "#f691b2": {"light":{"bg":"#d81b60","fg":"#ffffff"},"dark":{"bg":"#d85675","fg":"#131314"}},
  "#cd74e6": {"light":{"bg":"#8e24aa","fg":"#ffffff"},"dark":{"bg":"#a75aba","fg":"#131314"}},
  "#a47ae2": {"light":{"bg":"#9e69af","fg":"#ffffff"},"dark":{"bg":"#a479b1","fg":"#131314"}},
  "#7986cb": {"light":{"bg":"#7986cb","fg":"#ffffff"},"dark":{"bg":"#828bc2","fg":"#131314"}},
  "#33b679": {"light":{"bg":"#33b679","fg":"#ffffff"},"dark":{"bg":"#55b080","fg":"#131314"}},
  "#8e24aa": {"light":{"bg":"#8e24aa","fg":"#ffffff"},"dark":{"bg":"#a75aba","fg":"#131314"}},
  "#e67c73": {"light":{"bg":"#e67c73","fg":"#ffffff"},"dark":{"bg":"#d6837a","fg":"#131314"}},
  "#f6bf26": {"light":{"bg":"#f6bf26","fg":"#ffffff"},"dark":{"bg":"#e7ba51","fg":"#131314"}},
  "#f4511e": {"light":{"bg":"#f4511e","fg":"#ffffff"},"dark":{"bg":"#e3683e","fg":"#131314"}},
  "#039be5": {"light":{"bg":"#039be5","fg":"#ffffff"},"dark":{"bg":"#4b99d2","fg":"#131314"}},
  "#616161": {"light":{"bg":"#616161","fg":"#ffffff"},"dark":{"bg":"#7c7c7c","fg":"#131314"}},
  "#3f51b5": {"light":{"bg":"#3f51b5","fg":"#ffffff"},"dark":{"bg":"#6e72c3","fg":"#131314"}},
  "#0b8043": {"light":{"bg":"#0b8043","fg":"#ffffff"},"dark":{"bg":"#489160","fg":"#131314"}},
  "#d50000": {"light":{"bg":"#d50000","fg":"#ffffff"},"dark":{"bg":"#da5234","fg":"#131314"}},
};
