// Compile-time check that the Rust fixtures match the TS mirror (docs/02 section 5).
// Each fixture is regenerated by `cargo test` from src-tauri/src/commands/types.rs.
import { describe, expect, it } from 'vitest';
import type {
  AccountInfo,
  CalendarInfo,
  CalendarUpdated,
  ColorPalette,
  EditScope,
  EventDetail,
  EventDraft,
  GoaStatus,
  PushTestResult,
  Settings,
  ShowEvent,
  SyncStatus,
  ViewPayload,
} from './ipc';
import accountInfo from './fixtures/AccountInfo.json';
import calendarInfo from './fixtures/CalendarInfo.json';
import calendarUpdated from './fixtures/CalendarUpdated.json';
import colorPalette from './fixtures/ColorPalette.json';
import editScope from './fixtures/EditScope.json';
import eventDetail from './fixtures/EventDetail.json';
import eventDraft from './fixtures/EventDraft.json';
import goaStatus from './fixtures/GoaStatus.json';
import pushTestResult from './fixtures/PushTestResult.json';
import settings from './fixtures/Settings.json';
import showEvent from './fixtures/ShowEvent.json';
import syncStatus from './fixtures/SyncStatus.json';
import viewPayload from './fixtures/ViewPayload.json';

// JSON imports widen string literals to `string`, so the structural check runs on a widened
// copy of each interface: keys and nullability must match; literal unions are checked at runtime.
type Widen<T> = T extends string
  ? string
  : T extends (infer U)[]
    ? Widen<U>[]
    : T extends object
      ? { [K in keyof T]: Widen<T[K]> }
      : T;

// `satisfies` fails typecheck when the JSON shape drifts from the interface.
const accounts = accountInfo satisfies Widen<AccountInfo>[];
const calendars = calendarInfo satisfies Widen<CalendarInfo>[];
const updated = calendarUpdated satisfies Widen<CalendarUpdated>;
const palette = colorPalette satisfies Widen<ColorPalette>;
const scopes = editScope satisfies Widen<EditScope>[];
const detail = eventDetail satisfies Widen<EventDetail>;
const draft = eventDraft satisfies Widen<EventDraft>;
const pushResult = pushTestResult satisfies Widen<PushTestResult>;
const goa = goaStatus satisfies Widen<GoaStatus>;
const settingsValue = settings satisfies Widen<Settings>;
const show = showEvent satisfies Widen<ShowEvent>;
const status = syncStatus satisfies Widen<SyncStatus>;
const view = viewPayload satisfies Widen<ViewPayload>;

const SYNC_STATES = ['idle', 'syncing', 'error', 'auth_required'];
const ACCESS_ROLES = ['owner', 'writer', 'reader', 'freeBusyReader'];
const RESPONSES = ['needsAction', 'declined', 'tentative', 'accepted'];

// Reverse direction: every key of the interface must exist in the fixture object.
function keysOf<T extends object>(v: T): (keyof T)[] {
  return Object.keys(v) as (keyof T)[];
}

describe('IPC fixtures', () => {
  it('have the fields the UI reads', () => {
    expect(accounts.length).toBe(2);
    expect(calendars[0]?.default_reminders[0]?.method).toBe('popup');
    expect(view.occurrences[0]?.id).toContain('|');
    expect(keysOf(detail)).toContain('can_rsvp');
    expect(keysOf(draft)).toContain('add_meet');
    expect(palette.events).toHaveLength(11);
    expect(scopes).toEqual(['this', 'following', 'all']);
    expect(settingsValue.week_start).toBe(1);
    expect(settingsValue.hour_format).toBe('24');
    expect(updated.calendar_ids[0]?.calendar_id).toBe('local-personal');
    expect(status.state).toBe('syncing');
    expect(show.occurrence_id).toBeTruthy();
    expect(pushResult.ok).toBe(false);
    expect(goa.accounts[0]?.calendar_disabled).toBe(false);
  });

  it('use only the literal values of the unions', () => {
    for (const a of accounts) {
      expect(['local', 'google']).toContain(a.kind);
      expect(SYNC_STATES).toContain(a.sync_state);
    }
    for (const c of calendars) expect(ACCESS_ROLES).toContain(c.access_role);
    for (const o of view.occurrences) {
      expect(['confirmed', 'tentative']).toContain(o.status);
      if (o.my_response !== null) expect(RESPONSES).toContain(o.my_response);
      if (o.transparency !== null) expect(['opaque', 'transparent']).toContain(o.transparency);
    }
    for (const a of detail.attendees) expect(RESPONSES).toContain(a.response_status);
    expect(SYNC_STATES).toContain(status.state);
    expect(['24', '12']).toContain(settingsValue.hour_format);
    expect(settingsValue.theme).toBe('system');
  });
});
