#!/usr/bin/env node
// Generate src/styles/tokens.css from docs/design/tokens.json.
// Naming: --font-<role>-<prop>, --layout-<name>, --<component>-<prop>,
// --event-<id>-bg|fg|hover, --color-<name> (light values in :root, dark values
// under prefers-color-scheme: dark). Null values are skipped and reported, so the
// CSS never contains a guessed value. Keys "source*", "note*" and "name" are metadata.
// Font family values must already be valid CSS (quoted names), e.g. "\"Google Sans Flex\", Roboto".
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'docs/design/tokens.json'), 'utf8'));
const isMeta = k => k === 'name' || k.startsWith('source') || /(^|_)note$/.test(k) || k.startsWith('_');
const kebab = s => s.replace(/_/g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const skipped = [];

// A value may be a themed pair { "light": "...", "dark": "..." }: the light value goes to :root
// and the dark one to the prefers-color-scheme override, under the same name.
const isThemed = v => v && typeof v === 'object' && !Array.isArray(v) && 'light' in v && 'dark' in v && Object.keys(v).length === 2;
const darkOverrides = [];

function flatten(obj, prefix, out) {
  for (const [k, v] of Object.entries(obj)) {
    if (isMeta(k)) continue;
    const name = `${prefix}-${kebab(k)}`;
    if (v === null) { skipped.push(name); continue; }
    if (isThemed(v)) {
      if (v.light === null || v.dark === null) { skipped.push(name); continue; }
      out.push([name, String(v.light)]);
      darkOverrides.push([name, String(v.dark)]);
    } else if (typeof v === 'object' && !Array.isArray(v)) flatten(v, name, out);
    else out.push([name, Array.isArray(v) ? v.join(' ') : String(v)]);
  }
}

const shared = [], light = [], dark = [];
flatten(tokens.font, '--font', shared);
flatten(tokens.layout, '--layout', shared);
for (const [comp, props] of Object.entries(tokens.component)) flatten(props, `--${kebab(comp)}`, shared);
for (const [id, c] of Object.entries(tokens.color.event_palette)) {
  if (isMeta(id)) continue;
  for (const prop of ['bg', 'fg', 'hover']) {
    const name = `--event-${id}-${prop}`;
    if (c[prop] === null || c[prop] === undefined) skipped.push(name);
    else if (isThemed(c[prop])) { shared.push([name, c[prop].light]); darkOverrides.push([name, c[prop].dark]); }
    else shared.push([name, c[prop]]);
  }
}
for (const [id, c] of Object.entries(tokens.color.calendar_palette || {})) {
  if (isMeta(id)) continue;
  for (const prop of ['bg', 'fg']) {
    const name = `--calendar-${id}-${prop}`;
    if (isThemed(c[prop])) { shared.push([name, c[prop].light]); darkOverrides.push([name, c[prop].dark]); }
    else shared.push([name, c[prop]]);
  }
}
flatten(tokens.color.light, '--color', light);
flatten(tokens.color.dark, '--color', dark);
dark.push(...darkOverrides);

// Only the custom properties that hand-written stylesheets and components reference are emitted
// (measured.css carries its values literally): tens of thousands of inherited variables cost the
// webview real memory (docs/99, F8-T2). Every token stays in tokens.json.
import { readdirSync, statSync } from 'node:fs';
const used = new Set();
const walk = (d) => { for (const e of readdirSync(d)) { const p = resolve(d, e); if (statSync(p).isDirectory()) walk(p); else if (/\.(css|tsx?)$/.test(e) && !/tokens\.css$|measured\.css$/.test(e)) for (const m of readFileSync(p, 'utf8').matchAll(/var\((--[a-z0-9-]+)/g)) used.add(m[1]); } };
walk(resolve(root, 'src'));
const keep = ([n]) => used.has(n) || n.startsWith('--color-') || n.startsWith('--font-') || n.startsWith('--layout-') || n.startsWith('--event-') || n.startsWith('--calendar-');
const sharedKept = shared.filter(keep), lightKept = light.filter(keep), darkKept = dark.filter(keep);

const decl = (list, indent) => list.map(([n, v]) => `${indent}${n}: ${v};`).join('\n');
let css = `/* GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json. Do not edit. */\n`;
css += `:root {\n${decl([...sharedKept, ...lightKept], '  ')}\n}\n`;
if (darkKept.length) css += `@media (prefers-color-scheme: dark) {\n  :root {\n${decl(darkKept, '    ')}\n  }\n}\n`;

mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/tokens.css'), css);

// Layout numbers the renderer needs in JS (chip columns, initial scroll): same source, no retyping.
const layoutEntries = Object.entries(tokens.layout).filter(([k, v]) => !isMeta(k) && v !== null && typeof v !== 'object');
let ts = `// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json. Do not edit.\n`;
ts += `export const LAYOUT = {\n${layoutEntries.map(([k, v]) => `  ${k}: ${JSON.stringify(String(v))},`).join('\n')}\n} as const;\n`;
ts += `\n/** Numeric part of a layout token ("60px" → 60, "1.7" → 1.7). */\nexport const layoutNumber = (v: string): number => parseFloat(v);\n`;
writeFileSync(resolve(root, 'src/styles/layout.ts'), ts);

// Colour map for the renderer: the hex the backend stores (classic calendar colour from the API,
// or the modern event colour resolved by colorId) → the measured light/dark chip colours.
const toHex = (rgb) => { const m = String(rgb).match(/\d+/g); return m ? '#' + m.slice(0, 3).map((n) => Number(n).toString(16).padStart(2, '0')).join('') : String(rgb); };
const val = (v, theme) => (isThemed(v) ? v[theme] : v);
const entries = [];
for (const [id, c] of Object.entries(tokens.color.calendar_palette || {})) {
  if (isMeta(id) || !c.classic || !c.bg) continue;
  entries.push([c.classic.toLowerCase(), { light: { bg: toHex(val(c.bg, 'light')), fg: toHex(val(c.fg, 'light')) }, dark: { bg: toHex(val(c.bg, 'dark')), fg: toHex(val(c.fg, 'dark')) } }]);
}
for (const [id, c] of Object.entries(tokens.color.event_palette)) {
  if (isMeta(id) || !c.bg || c.bg === null) continue;
  const light = toHex(val(c.bg, 'light'));
  entries.push([light.toLowerCase(), { light: { bg: light, fg: toHex(val(c.fg, 'light')) }, dark: { bg: toHex(val(c.bg, 'dark')), fg: toHex(val(c.fg, 'dark')) } }]);
}
let pal = `// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json. Do not edit.\n`;
pal += `export interface ChipColors {\n  bg: string;\n  fg: string;\n}\n\n`;
pal += `/** Stored hex (classic calendar colour or modern event colour) → measured chip colours per theme. */\n`;
pal += `export const COLOR_MAP: Record<string, { light: ChipColors; dark: ChipColors }> = {\n${entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n')}\n};\n`;
const names = Object.entries(tokens.color.event_palette).filter(([id, c]) => !isMeta(id) && c && c.name).map(([id, c]) => `  ${JSON.stringify(id)}: ${JSON.stringify(c.name)},`);
pal += `\n/** Event colorId → Google's colour name (docs/04 section 7). */\nexport const EVENT_COLOR_NAMES: Record<string, string> = {\n${names.join('\n')}\n};\n`;
writeFileSync(resolve(root, 'src/styles/palette.ts'), pal);
console.log(`wrote src/styles/tokens.css: ${sharedKept.length + lightKept.length} light tokens, ${darkKept.length} dark tokens (of ${shared.length + light.length} measured)`);
if (skipped.length) console.log(`skipped ${skipped.length} null tokens (not measured yet), e.g. ${skipped.slice(0, 5).join(', ')}`);
