#!/usr/bin/env node
// Generate src/styles/tokens.css from docs/design/tokens.json.
// Naming: --font-<role>-<prop>, --layout-<name>, --<component>-<prop>,
// --event-<id>-bg|fg|hover, --color-<name> (light values in :root, dark values
// under prefers-color-scheme: dark). Null values are skipped and reported, so the
// CSS never contains a guessed value. Keys "source*", "note*" and "name" are metadata.
// Font family values must already be valid CSS (quoted names), e.g. "\"Google Sans Flex\", Roboto".
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'docs/design/tokens.json'), 'utf8'));
const isMeta = k => k === 'name' || k.startsWith('source') || k.includes('note');
const kebab = s => s.replace(/_/g, '-');
const skipped = [];

function flatten(obj, prefix, out) {
  for (const [k, v] of Object.entries(obj)) {
    if (isMeta(k)) continue;
    const name = `${prefix}-${kebab(k)}`;
    if (v === null) { skipped.push(name); continue; }
    if (typeof v === 'object' && !Array.isArray(v)) flatten(v, name, out);
    else out.push([name, Array.isArray(v) ? v.join(' ') : String(v)]);
  }
}

const shared = [], light = [], dark = [];
flatten(tokens.font, '--font', shared);
flatten(tokens.layout, '--layout', shared);
for (const [comp, props] of Object.entries(tokens.component)) flatten(props, `--${kebab(comp)}`, shared);
for (const [id, c] of Object.entries(tokens.color.event_palette)) {
  if (isMeta(id)) continue;
  for (const prop of ['bg', 'fg', 'hover']) {
    const name = `--event-${id}-${prop}`;
    if (c[prop] === null) skipped.push(name); else shared.push([name, c[prop]]);
  }
}
flatten(tokens.color.light, '--color', light);
flatten(tokens.color.dark, '--color', dark);

const decl = (list, indent) => list.map(([n, v]) => `${indent}${n}: ${v};`).join('\n');
let css = `/* GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json. Do not edit. */\n`;
css += `:root {\n${decl([...shared, ...light], '  ')}\n}\n`;
if (dark.length) css += `@media (prefers-color-scheme: dark) {\n  :root {\n${decl(dark, '    ')}\n  }\n}\n`;

mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/tokens.css'), css);
console.log(`wrote src/styles/tokens.css: ${shared.length + light.length} light tokens, ${dark.length} dark tokens`);
if (skipped.length) console.log(`skipped ${skipped.length} null tokens (not measured yet), e.g. ${skipped.slice(0, 5).join(', ')}`);
